//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sencilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> EventoID { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public Nullable<System.TimeSpan> HoraEliminacion { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
